Repository pagopa/pagopa-debt-position, pull requests merged in 2022-05, with the labels that each got.

#90 [PPD-157] Payment Option error
  README.md
  api-test/Debt Position - Local.postman_environment.json
  api-test/Debt Position.postman_collection.json
  api-test/azure.dev.postman_environment.json
  api-test/azure.uat.postman_environment.json
  gpd/openapi/openapi.json
  gpd/src/main/java/it/gov/pagopa/debtposition/model/payments/PaymentOptionModel.java
  gpd/src/main/resources/application-local.properties
  gpd/src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
  payments/src/main/java/it/gov/pagopa/payments/service/PartnerService.java
  payments/src/main/resources/application-local.properties
  payments/src/test/java/it/gov/pagopa/payments/endpoint/PartnerEndpointTest.java
Labels: bug

#103 [PPD-185] strategia rilasci versioning
  .devops/deploy-pipelines.yml
  .github/auto_assign.yml
  .github/workflows/assignee.yml
  .github/workflows/check_metadata_pr.yml
  .github/workflows/deploy.yml
  .github/workflows/sonar_analysis.yml
  .github/workflows/update_infra.yml
Labels: enhancement, gpd

#105 fix GH Action
  .github/workflows/check_metadata_pr.yml
Labels: gpd, ignore-for-release

#104 [PPD-171] change organization call
  api-test/Debt Position - Local.postman_environment.json
  api-test/Debt Position.postman_collection.json
  api-test/azure.dev.postman_environment.json
  api-test/azure.uat.postman_environment.json
  gpd/src/main/java/it/gov/pagopa/debtposition/controller/configuration/api/IConfigurationsController.java
  gpd/src/main/java/it/gov/pagopa/debtposition/controller/configuration/api/impl/ConfigurationsController.java
  gpd/src/main/java/it/gov/pagopa/debtposition/service/configurations/ConfigurationsService.java
  gpd/src/test/java/it/gov/pagopa/debtposition/controller/ConfigurationsControllerTest.java
  payments/src/main/java/it/gov/pagopa/payments/config/FeignConfig.java
  payments/src/main/java/it/gov/pagopa/payments/endpoints/validation/PaymentValidator.java
  payments/src/main/java/it/gov/pagopa/payments/model/PaaErrorEnum.java
  payments/src/main/java/it/gov/pagopa/payments/model/creditorinstitution/CreditorInstitution.java
  payments/src/main/java/it/gov/pagopa/payments/model/creditorinstitution/StationCreditorInstitution.java
  payments/src/main/java/it/gov/pagopa/payments/service/ApiConfigClient.java
  payments/src/main/java/it/gov/pagopa/payments/service/GpdClient.java
  payments/src/main/resources/application-local.properties
  payments/src/main/resources/application.properties
  payments/src/test/java/it/gov/pagopa/payments/endpoints/validation/PaymentValidatorTest.java
  payments/src/test/resources/application.properties
Labels: bug, payments
