Repository pagopa/pagopa-debt-position, pull requests merged in 2023-10, with the labels that each got.

#182 feat: Add SEND OpenAPI [PAGOPA-1267]
  openapi/openapi_external.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/debtposition/OpenApiGenerationTest.java
  src/test/resources/application.properties
Labels: ignore-for-release, size/large

#185 ci: Update integration test default env
  .github/workflows/integration_test.yml
Labels: ignore-for-release, size/small

#183 feat: [PAGOPA-1272] - Check Position on update fee
  .github/workflows/code_review.yml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
  src/main/java/it/gov/pagopa/debtposition/client/NodeClient.java
  src/main/java/it/gov/pagopa/debtposition/config/feign/AuthFeignConfig.java
  src/main/java/it/gov/pagopa/debtposition/config/feign/NodeFeignConfig.java
  src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/debtposition/model/checkposition/NodeCheckPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/model/checkposition/NodePosition.java
  src/main/java/it/gov/pagopa/debtposition/model/checkposition/response/NodeCheckPositionResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
  src/main/java/it/gov/pagopa/debtposition/util/CustomHttpStatus.java
  src/main/resources/application-h2.properties
  src/main/resources/application-local.properties
  src/main/resources/application.properties
  src/main/resources/db/migration/V008__ALTER_LAST_UPDATE_NOTIFICATIONFEE.sql
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
  src/test/resources/application.properties
Labels: enhancement, size/large

#184 feat:[PagoPa-1292]: smoke test
  Dockerfile
  docker/run_docker.sh
  integration-test/src/features/debt-position-manage.feature
  src/main/java/it/gov/pagopa/debtposition/model/checkposition/NodeCheckPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/util/CustomHttpStatus.java
  src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
Labels: bug, enhancement, gpd, size/small

#188 feat: [PagoPa-1296] Integration Test Enti Plurintermediati
  integration-test/src/.gitignore
  integration-test/src/features/debt-position-create-and-publish.feature
  integration-test/src/features/debt-position-manage.feature
  integration-test/src/step_definitions/support/clients/gpd_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/step_definitions/support/utility/request_builders.js
Labels: enhancement, size/small

#189 fix: Add ExceptionHandler for ConstraintViolationException [PAGOPA-1319]
  src/main/java/it/gov/pagopa/debtposition/exception/ErrorHandler.java
Labels: bug, size/small
