Repository pagopa/pagopa-debt-position, pull requests merged in 2023-11, with the labels that each got.

#187 fix: Update SwaggerConfig for grouped OpenAPI [PAGOPA-1304]
  openapi/openapi_external.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java
Labels: size/large

#190 chore: Fix integration test [PAGOPA-1330]
  .github/workflows/code_review.yml
  .identity/03_github_environment.tf
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/debt-position-manage.feature
  integration-test/src/features/debt-position-pay.feature
  integration-test/src/step_definitions/support/clients/gpd_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/steps.js
Labels: ignore-for-release, size/small

#172 ci: Remove az-devops deploy pipeline
  .devops/azure-templates/maven-versioning.yml
  .devops/deploy-pipelines.yml
Labels: gpd, size/large

#191 [PagoPa-1333] gpd metadata
  openapi/openapi_external.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentOptionMetadata.java
  src/main/java/it/gov/pagopa/debtposition/entity/Transfer.java
  src/main/java/it/gov/pagopa/debtposition/entity/TransferMetadata.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPOEntityToPOWithDebtor.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionWithDebtorInfoModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/TransferModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionMetadataModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentOptionModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/TransferMetadataModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentOptionMetadataModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentOptionModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/response/TransferMetadataModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/response/TransferModelResponse.java
  src/main/resources/db/migration/V009__ADD_METADATA_TABLES.sql
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/dto/PaymentOptionDTO.java
  src/test/java/it/gov/pagopa/debtposition/dto/PaymentOptionMetadataDTO.java
  src/test/java/it/gov/pagopa/debtposition/dto/TransferDTO.java
  src/test/java/it/gov/pagopa/debtposition/dto/TransferMetadataDTO.java
  src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
Labels: size/large

#192 feat: Add new metadata when create payment position [PAGOPA-1348]
  README.md
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
Labels: enhancement, size/small

#194 [PAGOPA-1348] chore: rollback PO_TYPE metadata
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
Labels: gpd, size/small

#195 feat: [PagoPA-1361] Bulk Loading
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/steps.js
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/validator/ValidDebtPositionsSize.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/validator/ValidMaxDebtPositions.java
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/MultiplePaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
  src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/debtposition/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/dto/MultiplePaymentPositionDTO.java
  src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
  src/test/resources/application.properties
Labels: enhancement, size/large
