Repository pagopa/pagopa-debt-position, pull requests merged in 2023-07, with the labels that each got.

#158 AKS autoscaling via KEDA [PAGOPA-1040]
  gpd/src/main/resources/application-h2.properties
  gpd/src/main/resources/application-local.properties
  gpd/src/main/resources/application.properties
  gpd/src/test/resources/application.properties
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  report/pom.xml
Labels: enhancement, gpd, size/small

#161 fix: Update Actions
  .github/workflows/create_dashboard.yaml
  .github/workflows/db_migration_with_github_runner.yml
  .github/workflows/integration_test.yml
  .github/workflows/release_deploy.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_internal.json
  pom.xml
Labels: gpd, size/small

#162 chore: Update README.md
  README.md
Labels: gpd

#165 Update GH Runner
  .github/workflows/db_migration_with_github_runner.yml
  .github/workflows/deploy_with_github_runner.yml
  load-test/src/test-types/constant.json
  load-test/src/test-types/smoke.json
Labels: bug, gpd

#164 Tuning performance test
  .identity/00_data.tf
  .identity/03_github_environment.tf
  load-test/src/just_payments_workflow.js
  load-test/src/modules/data.js
  load-test/src/modules/helpers.js
  load-test/src/test-types/constant.json
  load-test/src/test-types/smoke.json
Labels: size/small

#166 fix: Url metrcs autoscaling prod
  helm/values-prod.yaml
Labels: size/small
