Repository pagopa/pagopa-debt-position, pull requests merged in 2023-12, with the labels that each got.

#196 [BCDR] feat: Update Pod affinity
  .gitignore
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small

#197 PAGOPA-1392 fixing bulk null pointer metadata
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
Labels: bug, size/large

#198 bug: [PAGOPA-1393] switch to expired error
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
  src/test/java/it/gov/pagopa/debtposition/dto/PaymentPositionDTO.java
Labels: bug, size/small
