Repository pagopa/pagopa-debt-position, pull requests merged in 2024-03, with the labels that each got.

#213 chore: Update pg connection params
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: size/small, patch

#214 [PAGOPA-1588] feat: add bulk update
  helm/values-prod.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/repository/specification/PaymentPositionByIUPDList.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
  src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/mock/DebtPositionMock.java
Labels: size/large

#217 feat: [PAGOPA-1632] update notificationfee
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/step_definitions/support/utility/data.js
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
  src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/NotificationFeeUpdateModel.java
  src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
  src/test/java/it/gov/pagopa/debtposition/controller/PaymentsControllerTest.java
Labels: size/large, patch
