Repository pagopa/pagopa-debt-position, pull requests merged in 2024-12, with the labels that each got.

#275 feat: [PagoPA-2459] - expired status
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_internal_massive.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
  src/main/java/it/gov/pagopa/debtposition/util/CommonUtil.java
  src/main/java/it/gov/pagopa/debtposition/util/Constants.java
  src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
  src/main/java/it/gov/pagopa/debtposition/util/PublishPaymentUtil.java
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/scheduler/ExpiredPositionsSchedulerTest.java
Labels: size/small

#281 Update gha
  .github/workflows/check_pr.yml
  .github/workflows/code_review.yml
  .github/workflows/github_scripts/check_required_labels.js
  .github/workflows/github_scripts/check_size.js
  .github/workflows/release_deploy.yml
  .pre-commit-config.yaml
  docker/docker-compose-local.yml
  docker/run_docker_smoke.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
Labels: size/large, patch

#277 bug: [PagoPa-2421] - advisory lock
  .github/workflows/db_migration_with_github_runner.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  apdFlywayConfig.conf
  pom.xml
Labels: bug, size/small

#284 chore: Update identity
  .identity/00_data.tf
  .identity/03_github_environment.tf
  .identity/terraform.sh
Labels: skip
