Repository pagopa/pagopa-debt-position, pull requests merged in 2024-05, with the labels that each got.

#226 feat: [PAGOPA-1719] - new pull column
  README.md
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentPositionModelBaseResponse.java
  src/main/resources/db/migration/V015__ALTER_PULL.sql
Labels: size/large

#227 fix: Update `Dockerfile` file for app-insights log [PAGOPA-1727]
  Dockerfile
Labels: bug, size/small

#229 fix: Run with app-insight agent [PAGOPA-1727]
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  local.settings.json.example
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
Labels: bug

#230 bug: [PAGOPA-1737] lock acquisition exception
  src/main/java/it/gov/pagopa/debtposition/repository/PaymentPositionRepository.java
Labels: size/small

#235 chore: Update openapi_external.json
  openapi/openapi_external.json
Labels: ignore-for-release

#234 chore: Adjust `getOrganizationDebtPositions` default limit [PAGOPA-1757]
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
Labels: size/small, patch

#231 log: enable ELK logging [PAGOPA-1718]
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/IDebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
  src/main/resources/logback-spring.xml
Labels: size/large, OER

#232 feat: Update state congruence [PAGOPA-1718]
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/actions/PaymentPositionActionsService.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
Labels: size/small, patch

#237 chore: Refactoring slack report
  .github/workflows/report.yml
  gpd-report/.env.sample
  gpd-report/main.go
  gpd-report/repository/repository.go
Labels: size/small
