Repository pagopa/pagopa-debt-position, pull requests merged in 2024-11, with the labels that each got.

#261 [PAGOPA-2354] feat: Update `unique_transfer` constraint
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/resources/db/migration/V018__UPDATE_UNIQUE_TRANSFER_CONSTRAINT.sql
Labels: size/small, patch

#265 feat: Upd `SPRING_DATASOURCE_URL`
  helm/values-dev.yaml
  pom.xml
Labels: size/small

#266 chore: Update SwaggerConfig.java
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_internal_massive.json
  openapi/openapi_send.json
  src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java
Labels: size/large

#271 fix: Update bulk APIs payload max size
  src/main/java/it/gov/pagopa/debtposition/model/pd/MultipleIUPDModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/MultiplePaymentPositionModel.java
Labels: size/small, patch
