Repository pagopa/pagopa-debt-position, pull requests merged in 2024-10, with the labels that each got.

#251 [PAGOPA-2128)] feat: Add pay_stand_in column
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
  src/main/resources/db/migration/V016__ADD_PAY_STAND_ID.sql
Labels: size/small

#250 [PAGOPA-2098] fix(Stamp): Add validation check
  src/main/java/it/gov/pagopa/debtposition/model/pd/TransferModel.java
Labels: bug, size/small

#252 feat(logging): enhanced log + json format
  Dockerfile
  docker/applicationinsights.json
  docker/run_docker.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  src/main/java/it/gov/pagopa/debtposition/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java
  src/main/java/it/gov/pagopa/debtposition/controller/BaseController.java
  src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/actions/api/impl/DebtPositionActionsController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/impl/DebtPositionController.java
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentPosition.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionWithDebtorInfoModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/scheduler/ExpiredPositionsScheduler.java
  src/main/java/it/gov/pagopa/debtposition/scheduler/HistoricizationScheduler.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/actions/PaymentPositionActionsService.java
  src/main/java/it/gov/pagopa/debtposition/util/CommonUtil.java
  src/main/java/it/gov/pagopa/debtposition/util/DebtPositionValidation.java
  src/main/java/it/gov/pagopa/debtposition/util/SchedulerUtils.java
  src/main/resources/application.properties
  src/main/resources/logback-local.xml
  src/main/resources/logback-spring.xml
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPaidPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPartiallyPaidPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPartiallyReportedPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentReportedPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/scheduler/ExpiredPositionsSchedulerTest.java
  src/test/resources/application.properties
Labels: size/large

#254 feat [PAGOPA-2241] query optimization
  src/main/resources/db/migration/V017__IDX_TO_INCREASE_JOIN_PERFORMANCE.sql
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerTest.java
Labels: size/small

#255 chore(smapling): change docker image
  Dockerfile
  docker/applicationinsights.json
  docker/run.sh
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/debtposition/config/LoggingAspect.java
  src/main/java/it/gov/pagopa/debtposition/scheduler/ExpiredPositionsScheduler.java
  src/main/java/it/gov/pagopa/debtposition/scheduler/HistoricizationScheduler.java
  src/main/java/it/gov/pagopa/debtposition/util/SchedulerUtils.java
  src/main/resources/logback-spring.xml
Labels: size/small, patch

#257 chore(flag-pull): Remove Pull Flag
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/response/PaymentPositionModelBaseResponse.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPaidPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPartiallyPaidPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentPartiallyReportedPaymentsControllerTest.java
  src/test/java/it/gov/pagopa/debtposition/controller/concurrent/ConcurrentReportedPaymentsControllerTest.java
Labels: size/large, patch

#259 chore: Fix Dev deploy 2 pglfex
  helm/values-dev.yaml
Labels: ignore-for-release, size/small
