Repository pagopa/pagopa-debt-position, pull requests merged in 2025-01, with the labels that each got.

#273 [PAGOPA-2446] refactoring: Update status on-the-fly
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/src/features/debt-position-pay.feature
  integration-test/src/step_definitions/support/clients/gpd_client.js
  integration-test/src/step_definitions/support/logic/common_logic.js
  integration-test/src/step_definitions/support/logic/gpd_logic.js
  integration-test/src/step_definitions/support/steps.js
  integration-test/src/step_definitions/support/utility/data.js
  integration-test/src/step_definitions/support/utility/helpers.js
  integration-test/src/step_definitions/support/utility/request_builders.js
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_internal.json
  openapi/openapi_internal_massive.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/model/enumeration/DebtPositionStatus.java
  src/main/java/it/gov/pagopa/debtposition/service/payments/PaymentsService.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/actions/PaymentPositionActionsService.java
Labels: size/small, patch

#285 feat: PAGOPA-2480 V3 API development
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi_external.json
  openapi/openapi_external_massive.json
  openapi/openapi_external_v3.json
  openapi/openapi_internal.json
  openapi/openapi_internal_massive.json
  openapi/openapi_send.json
  pom.xml
  src/main/java/it/gov/pagopa/debtposition/DebtPositionApplication.java
  src/main/java/it/gov/pagopa/debtposition/config/SwaggerConfig.java
  src/main/java/it/gov/pagopa/debtposition/controller/BaseController.java
  src/main/java/it/gov/pagopa/debtposition/controller/payments/api/IPaymentsController.java
  src/main/java/it/gov/pagopa/debtposition/controller/payments/api/impl/PaymentsController.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/actions/api/v3/DebtPositionActionsControllerV3.java
  src/main/java/it/gov/pagopa/debtposition/controller/pd/crud/api/v3/DebtPositionControllerV3.java
  src/main/java/it/gov/pagopa/debtposition/entity/PaymentOption.java
  src/main/java/it/gov/pagopa/debtposition/exception/AppError.java
  src/main/java/it/gov/pagopa/debtposition/exception/ErrorHandler.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPOEntityToPOWithDebtor.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertPPModelToPPEntityForUpdate.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConvertTransferToTransferResponse.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConverterV3PPEntityToModel.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConverterV3PPEntityToModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/mapper/ConverterV3PPModelToEntity.java
  src/main/java/it/gov/pagopa/debtposition/mapper/utils/UtilityMapper.java
  src/main/java/it/gov/pagopa/debtposition/model/IPaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/PaymentOptionWithDebtorInfoModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/payments/response/TransferModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/DebtorModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/PaymentPositionModel.java
  src/main/java/it/gov/pagopa/debtposition/model/pd/TransferMetadataModel.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/InstallmentMetadataModel.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/InstallmentModel.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/PaymentOptionModelV3.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/PaymentPositionModelV3.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/response/InstallmentMetadataModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/response/InstallmentModelResponse.java
  src/main/java/it/gov/pagopa/debtposition/model/v3/response/PaymentOptionModelResponseV3.java
  src/main/java/it/gov/pagopa/debtposition/service/pd/crud/PaymentPositionCRUDService.java
  src/main/java/it/gov/pagopa/debtposition/util/ObjectMapperUtils.java
  src/test/java/it/gov/pagopa/debtposition/controller/DebtPositionControllerV3Test.java
Labels: enhancement, dev, uat

#272 feat: PagoPA-2427 migration service type adjustment 1️⃣ ㏈
  src/main/resources/db/migration/V022__UPDATE_PP_SERVICE_TYPE.sql
Labels: documentation, size/small, dev, uat, prod

#278 feat: PagoPA-2483 V3 DB debtor fields 2️⃣ ㏈
  src/main/resources/db/migration/V023__ALTER_PO_DEBTOR_FIELDS.sql
Labels: enhancement, gpd, size/small, dev, uat, prod
